### ISSUE TITLE
Некорректное определение класса прибора

### ISSUE THREAD

**Issue by MisterSidodsh** [MisterSidodsh/Electro_v2_dll#2]
В классе AddOrEdditForm происходит некорректное определение класса прибора из-за неверно расставленных операторов if и  else. Нужно убрать else оставит только if и убрать сравнение прибора с нулем в самом первом случае.

[ОшибкаЗдесь](https://github.com/MisterSidodsh/Electro_v2_dll/blob/master/Electro_v2/AddOrEditForm.cs)

**Comment by iwouldnot** [comment]
Пофиксил в #3. Проверяй-закрывай

**Comment by MisterSidodsh** [comment]
Все норм, можно закрывать
